### PR TITLE
Exporting

### PR DESCRIPTION
**Pull request by NCrusher74**
Hi. Bet you wondered where I fell off the planet to. I've been pretty down with my health issues the past couple months, but I'm starting to get better and trying to pick up working on things again. Hope you're well.

I'm trying add the ability to export metadata and chapter .cue files from my audiobooks.

I have the start time for each chapter in milliseconds, and using that, I can format an accurate MM:SS string as follows:

```swift
extension Int {
    var cueTimeStamp: String {
        // starting in milliseconds where chapter begins
        let interval: TimeInterval = TimeInterval(self / 1000)
        
        let formatter = DateComponentsFormatter()
        formatter.unitsStyle = .positional
        formatter.allowedUnits = [ .minute, .second ]
        formatter.zeroFormattingBehavior = .pad
        
        return formatter.string(from: interval) ?? ""
    }
}
```

However, that doesn't work for .cue files. A typical file for an audiobook looks like this:

```
  TRACK 01 AUDIO
    TITLE "Chapter 1"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Chapter 2"
    INDEX 01 11:25:55
  TRACK 03 AUDIO
    TITLE "Chapter 3"
    INDEX 01 47:41:30
  TRACK 04 AUDIO
    TITLE "Chapter 4"
    INDEX 01 66:10:39
```

[this page](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Most_often_used) explains what the unit after that second colon is:

> Index points are specified in MM:SS:FF format... FF is the number of frames (there are seventy five frames to one second)

So I can certainly perform the calculations to get there. However, while I can find lots of posts about how to round decimals to a certain number of places, there aren't many about rounding integers (which probably means I'm missing something obvious, or at least wording my search incorrectly.)

This is my first time using `NumberFormatter`, and the way I've arrived there appears to be accurate, but terribly clunky and I'm sure there must be a better way?

```swift
extension Int {
    var cueTimeStamp: String {
        let interval: TimeInterval = TimeInterval(self / 1000)
        
        let formatter = DateComponentsFormatter()
        formatter.unitsStyle = .positional
        formatter.allowedUnits = [ .minute, .second ]
        formatter.zeroFormattingBehavior = .pad
        
        let mmssFormatted = formatter.string(from: interval) ?? ""
        
        let remainder = self % 1000
        let frames = (Double(remainder) * 0.075)
        
        let numFormatter = NumberFormatter()
        numFormatter.maximumFractionDigits = 0
        numFormatter.maximumIntegerDigits = 2
        numFormatter.minimumIntegerDigits = 2
        let num = frames as NSNumber
        let ffFormatted = numFormatter.string(from: num)
        
        return "\(mmssFormatted):\(ffFormatted ?? "00")"
    }
}
```

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
I think that’s right. (It is simple enough I probably would not have used a formatter, but I don’t know which strategy is actually more efficient.)

**Comment by NCrusher74** [comment]
My first inclination wasn't to use the formatter, but I couldn't find a rounding strategy for limiting an `Int` (or possibly a `Double`) to two digits. It seems weird to me that I've never encountered that situation, but I guess I haven't, or if I have it was so long ago I don't remember where I handled it or how.

I could find (and have used) various [rounding strategies](https://stackoverflow.com/a/38036978/12199136) for doubles. I have this in my convenience extensions library:

```swift
    func decimalPlaces(_ fractionDigits: Int) -> Double {
        let multiplier = pow(10, Double(fractionDigits))
        return Darwin.round(self * multiplier) / multiplier
    }
```

But I can't find any information on how to take an integer that may be 3-4 digits and round it to two digits. Most of the ways I've tried end up rounding to the tens place, which isn't what I need.

**Comment by NCrusher74** [comment]
Kinda-sorta in the same vein, I'm wondering if you would have any recommendations for making my conversion to and from these strings any more accurate:

This is my function to convert milliseconds to the "MM:SS:FF" string described above when exporting chapters in a .cue file:

```swift
    // startTime is in milliseconds, convert to mm:ss:FF
    var cueTimeStamp: String {
        let interval: TimeInterval = TimeInterval(self / 1000)
        
        let formatter = DateComponentsFormatter()
        formatter.allowedUnits = [ .minute, .second ]
        formatter.zeroFormattingBehavior = .pad
        
        let mmssFormatted = formatter.string(from: interval) ?? ""
        
        let remainder = self % 1000
        let frames = (Double(remainder) * 0.075)
        let framesRounded = Int(frames.decimalPlaces(0))
        return "\(mmssFormatted):" + "\(framesRounded)".leadingZeros()
    }
```

That results in 2861400 millseconds being converted to the string "47:41:30".

When converting that string back, however, I end up with 2861395 ms.

This is my calculation for converting it back:

```swift
extension Array where Element == String {
    mutating func interpretTimeStampStrings() -> Int {
        guard self.count == 3 else {
            return 0
        }

        let minutesString = self.extractFirst()
        let minutes: Int
        if let int = Int(minutesString)  {
            minutes = int
        } else {
            minutes = 0
        }
        
        let secondsString = self.extractFirst()
        var seconds = minutes * 60
        if let int = Int(secondsString) {
            seconds += int
        }
        
        var milliseconds = seconds * 1000
        let milliString = self.extractFirst()
        if let int = Int(milliString) {
            let millis = Double(int) / 0.075
            milliseconds += Int(millis)
        }

        return milliseconds
    }
}
```

While not a huge difference, if done too many times, it could end up cumulatively drifting off target? (not that it would be repeated enough to be a problem, mostly I'm just being nitpicky about the inaccuracy.)

I'm sure it's the conversion of doubles to ints and vice versa causing the problem, but maybe there's a more accurate way to handle that conversion?

**Comment by SDGGiesbrecht** [comment]
Well 75 ∶ 1000 reduces to 3 ∶ 40, so there will inevitably be rounding required in some conversions. However, 400 ms ↔︎ 30 frames _exactly_, so I cannot fathom where the 5 ms are vanishing. And your code _looks_ correct.

**Comment by NCrusher74** [comment]
Okay, so the conversion of the 400 to 30 frames is correct, but the conversion from 30 frames back to milliseconds is wrong.

Yeah, this makes no sense. 30 / 0.075 is 400, and the fact that 30 is being converted to a double shouldn't introduce any errors because there's no rounding required. And converting that 400 back to an integer shouldn't either. 

And yeah, I knew it there would have to be rounding and that rounding would lose accuracy, but I'm hoping to minimize it if possible?

Time to run some tests in a playground and see if I can figure out where the inaccuracy is creeping in.

**Comment by NCrusher74** [comment]
Okay, I think I may have gotten my files confused and was using a different .cue file created by a different app (rather than one I exported) in my tests. So the chapters I was reading from the audio file prior to importing the chapters from the .cue were just a teeny bit different than the ones I was actually working with.

Nice to know I'm not entirely crazy. Just...slow on the uptake.

**Comment by NCrusher74** [comment]
Okay, I've been staring at this for days and now my eyes have crossed and it's become a blur of meaningless numbers to me. Maybe talking it through here will make them make sense to me again.

WAYYY back last year, when I was developing SwiftTaggerMP4, you may remember me discussing the `stts` (sample-to-time) atom, wherein the data about the duration of each sample contained in the media is stored.

The `sampleTable` property of this atom is this: 
```swift
    var sampleTable: [(sampleCount: Int, sampleDuration: Double)]
```

The reason it's stored that way is because, if multiple _consecutive_ samples have the same duration, they're stored as a single entry in the table, where `sampleCount` is the number of consecutive samples with a duration, followed by the duration itself.

Without thinking about the implications, while testing my chapter import/export functionality, I created a bunch of chapters with the same, 25-minute duration (except for the last one, because I didn't go all the way through the media sample I'm working with.) And in the process, uncovered a bug I never would have known was there otherwise, because my previous testing had involved chapters of different durations.

So my duration array look like this:

```
[1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 1500000.0, 2543065.0]
```

That SHOULD be stored in the `stts` atom as:

```
[(sampleCount: 17, sampleDuration: 1500000.0), (sampleCount: 1, sampleDuration: 2543065.0)]
```

Instead, what I'm getting is:

```
[(sampleCount: 1, sampleDuration: 1500000.0), (sampleCount: 17, sampleDuration: 2543065.0)]
```

So, clearly that's reversed from what it should be.

And the problem is occurring before the new file is being written, because that is the sample table as it's being read upon parsing the atom.

My `ChapterHandler` structure that deals with the converting chapters to atoms and vice versa, has this function, which I think you helped me build?

```swift
    func calculateDurationsFromStartTimes(mediaDuration: Double) -> [Double] {
        var chapterDurations = [Double]()
        let enumeratedStarts = chapterStarts.enumerated()
        let firstStart = chapterStarts.first ?? 0

        // Handle all but the last one.
        for (index, startTime) in enumeratedStarts.dropLast() {
            let followingTime = chapterStarts[chapterStarts.index(after: index)]
            chapterDurations.append(Double(followingTime) - Double(startTime))
        }
        
        // Handle the last one.
        let lastStart = chapterStarts.last ?? firstStart
        chapterDurations.append(mediaDuration - Double(lastStart))
        // print(chapterDurations)
        return chapterDurations
    }
```

And that is called and turned into the `sampleTable` described previously when I initialize the atom to create the chapter track, which is where I think my problem actually lies, because that print statement at the end of the function yields the duration array I included above, which looks correct.

```swift
    init(chapterHandler: ChapterHandler,
         mediaDuration: Double) throws {
        let durationArray = chapterHandler.calculateDurationsFromStartTimes(
            mediaDuration: mediaDuration)
 
       guard !durationArray.isEmpty else {
            throw StblError.SampleDurationArrayIsEmpty
        }

        var entries = [(sampleCount: Int, sampleDuration: Double)]()
        var previous = 0.0
        var count = 1

        for duration in durationArray {
            if duration == previous {
                // increase the count by 1, but don't store it in the tablet yet
                count += 1 
            } else {
                // store the number of samples with the previous duration
                let entry = (count, duration) 
                entries.append(entry)
  
              // update previous to current duration
                previous = duration
 
               // reset the count
                count = 1
            }
        }
        
        self.sampleTable = entries
        // yadda yadda other properties and super-init yadda
    }
```

I'm circling around the answer, I know I am, but I just can't *see* it. It has something to do with the handling of the very first chapter.

I start with a `previous` initialized as `0.0` which is a safe value, as it will be overwritten; there is simply no way a chapter can have a 0 duration (because ultimately chapters are stored in a dictionary keyed by their start times, so two chapters _can't_ have the same start time.)

I _think_ the problem may be this line:
`let entry = (count, duration)`.

Because that line is using the _current_ duration, when what I want is the _previous_ duration. However...

Changing it to:
`let entry = (count, previous) `

Results in this sampleTable:
```
[(sampleCount: 1, sampleDuration: 0.0), (sampleCount: 17, sampleDuration: 1500000.0)]
```

Which gets me the `(sampleCount: 17, sampleDuration: 1500000.0)` that I should have, but drops the last chapter's duration and adds a 0.0-duration chapter at the beginning, because of course the first chapter isn't equal to `0.0` so it creates an sampleTable entry for that initial value of `previous` and a new sampleTable entry for everything else (except that last.)

I think maybe this is one of those times where I just can't avoid force-unwrapping, which should be safe because I have that `guard` statement in there, right?

So what I need is something more like...

```swift
        guard !durationArray.isEmpty else {
            throw StblError.SampleDurationArrayIsEmpty
        }

        var entries = [(sampleCount: Int, sampleDuration: Double)]()
        var previous = durationArray.first!
        var count = 1

        for duration in durationArray.dropFirst() {
            if duration == previous {
                count += 1
            } else {
                // store the number of samples with the previous duration
                let entry = (count, previous)
                entries.append(entry)

                // update previous to current duration
                previous = duration

                // reset the count
                count = 1
            }
        }
```

But I'm not sure that's going to get the last duration into the table. Stand by...testing it.

Nope. Last duration is still missing:

```
[(sampleCount: 17, sampleDuration: 1500000.0)]
```

I need something more along the lines of this:

```swift
        for (index, duration) in durationArray.enumerated().dropFirst() {
            if duration == previous, index != durationArray.endIndex {
                count += 1
            } else {
                if index == durationArray.endIndex,
                   duration == previous {
                    count += 1
                    let entry = (count, previous)
                    entries.append(entry)
                } else if index == durationArray.endIndex {
                    let entry = (1, duration)
                    entries.append(entry)
                } else {
                    // store the number of samples with the previous duration
                    let entry = (count, previous)
                    entries.append(entry)
                    
                    // update previous to current duration
                    previous = duration
                    
                    // reset the count
                    count = 1
                }
            }
        }
```

But that isn't working either. The last entry is still being omitted from the sample table.

(hours of trying things later)
I finally have something that works, but now I'm worried that it's going to cause problems with other files?

```swift
        // force-unwrap should be safe here due to the guard statement
        // using an `extractFirst` helper extension for `Array where Element == Double`
        var previous = durationArray.extractFirst()!
        let last = durationArray.last!
        var count = 1

        // handle all except the last
        while !durationArray.dropLast().isEmpty {
            let current = durationArray.extractFirst()!
            
            if current == previous {
                 count += 1
            } else {
                // store the number of samples with the previous duration
                let entry = (count, previous)
                entries.append(entry)
                
                // update previous to current duration
                previous = current
                
                // reset the count
                count = 1
            }
        }
        
        // now handle the last
        if last == previous {
            count += 1
            let lastEntry = (count, last)
            entries.append(lastEntry)
        } else {
            // handle any that have been counted but not appended yet
            entries.append((count, previous))

            let lastEntry = (1, last)
            entries.append(lastEntry)
        }
```

I'm side-eying it hard but I think it's the best I'll get for now?

**Comment by SDGGiesbrecht** [comment]
Basically, the original problem was that each element of your iteration was looking at the one before it; the first iteration was reaching into the void for its “predecessor” and the last element had no succeeding iteration looking back at it.

Your solution is on the right track. Let me help clean it up a little:

```swift
guard let first = durationArray.first else {
  throw StblError.SampleDurationArrayIsEmpty
}

var entries = [(sampleCount: Int, sampleDuration: Double)]()
var currentDuration = first
var count = 1
func registerPending() {
  entries.append((count, currentDuration))
}

for duration in durationArray.dropFirst() {
  if duration == previous {
    // increase the count by 1, but don’t register it yet, since there might be more to come
    count += 1 
  } else {
    // new duration, so first register whatever is pending
    registerPending()

    // then start counting this duration
    currentDuration = duration
    count = 1
  }
}
// register whatever is left over
registerPending()

self.sampleTable = entries
```

**Comment by NCrusher74** [comment]
Yeah, that is a lot tidier, and sidesteps force unwrapping.

That whole thing should not have taken me nearly as long as it did to get to the messy solution I landed on. Between my health this year and an injury that is making it painful for me to use the computer even when my health permits me to get something done, my brain is just...not doing the thought thing very well. I'm trying to keep working on this, because I'm worried that I'm going to forget everything I learned if I leave it alone too long, but I'm being exceptionally stupid on the problem solving front (which is a large part of why I've gone back to working on back-end code rather than trying to work on the interface stuff; at least working on the back-end stuff, I'm marginally competent at what I'm trying to accomplish.

**Comment by NCrusher74** [comment]
In case you were curious about how badly I CAN'T brain this week, I just spent all day trying to figure out where I was going wrong in parsing and reproducing the `chpl` atom.

I finally determined that the atom uses a different unit of measurement than the milliseconds I had assumed, but I couldn't figure out what unit it actually _was_, and there is no documentation anywhere about that atom. All I knew was that it wasn't nanoseconds, because I was missing two zeros for that to be the case.

So I've spent the last seven hours looking at the way Mp4v2 handles it, and still couldn't figure it how I was supposed to calculate the unit of measurement.

When, in fact, [the answer was plainly spelled out and was staring me in the face the entire time](https://github.com/NCrusher74/Mp4v2-SPM/blob/1b65d63bf33952380d233bcdef5660fdc745e8ad/src/atom_chpl.cpp#L47)

**Pull request merged**
